version: '3.8'
services:
  database:
    container_name: database
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: music
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
#    volumes:
#      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
#      - ./database/data:/var/lib/postgresql