services:
  database:
    container_name: database
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: music
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
    ports:
      - "5435:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8083:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/music
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: pass
      STORAGE_MP3_PATH: /app/music/songs
      SONGS_JSON_PATH: /app/music/data/songs.json
      JWT_SECRET: "kPxo1WznfjNQjTpbKCgj435rhgOI9TCkIuMhdZPBrPo="
      CORS_ALLOWED_ORIGINS: "http://localhost:5175"
    volumes:
      - ${HOME}/Music/musicapp/mp3:/app/music/songs
      - ${HOME}/Music/musicapp/data:/app/music/data
    depends_on:
      - database

  frontend:
    container_name: frontend
    build:
      context: ./music-ui
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:8083
    restart: unless-stopped
    ports:
      - "5175:80"
    depends_on:
      - backend