spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.root=WARN
logging.level.io.github.deeqma=DEBUG
logging.level.org.springframework.test=INFO
logging.level.org.testcontainers=INFO

logging.level.org.hibernate.orm.jdbc.bind=TRACE


jwt.secret=kPxo1WznfjNQjTpbKCgj435rhgOI9TCkIuMhdZPBrPo=