# File Storage Properties
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=30MB

storage.mp3.path=src/main/resources/localstorage/mp3

spring.datasource.url=jdbc:postgresql://localhost:5432/music
spring.datasource.username=admin
spring.datasource.password=pass

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true


# generate in terminal: openssl rand -base64 32
jwt.secret=kPxo1WznfjNQjTpbKCgj435rhgOI9TCkIuMhdZPBrPo=