package io.github.deeqma.music.error;

public enum ErrorType {

    Duplicated_SONG,
    FILE_NOT_FOUND,
    SONG_NOT_FOUND,
    PLAYLIST_NOT_FOUND,
    SONG_ALREADY_IN_PLAYLIST,
    LIKED_SONG_ALREADY_EXISTS,
    SONG_NOT_IN_PLAYLIST,
    LIKED_SONG_NOT_FOUND,
    PLAYLIST_ALREADY_EXISTS,
    FILE_STORAGE_ERROR,
    PLAYLIST_EMPTY,
    INVALID_DATE,
    MP3_ALREADY_EXIST

}
