package io.github.deeqma.music.error;

public enum ErrorType {

    PLAYLIST_SHARE_NOT_ALLOWED,
    PLAYLIST_SHARE_ALREADY_EXISTS,
    PLAYLIST_LIMIT_REACHED,
    USER_NOT_FOUND,
    DUPLICATED_SONG,
    FILE_NOT_FOUND,
    SONG_NOT_FOUND,
    PLAYLIST_NOT_FOUND,
    SONG_ALREADY_IN_PLAYLIST,
    LIKED_SONG_ALREADY_EXISTS,
    SONG_NOT_IN_PLAYLIST,
    LIKED_SONG_NOT_FOUND,
    PLAYLIST_ALREADY_EXISTS,
    FILE_STORAGE_ERROR,
    PLAYLIST_EMPTY,
    INVALID_DATE,
    MP3_ALREADY_EXIST,
    NOT_FOUND,
    TOKEN_GENERATION_FAILED,
    ALREADY_EXISTS,
    BAD_CREDENTIALS

}
